Helios/Interfaces/DirectX/DirectXControllerInterface.cs
This is a fix for BlueFinBima#235 and BlueFinBima#231.
I think the bug is probably that the GUID is stored in the profile in the first place which seems a pretty fragile thing to do.
This might possibly be added to the pre-filght, but I'm not sure that we want to make a big deal of this because getting the user to update the GUID in the profile isn't really a sustainable approach.
=> DirectXInput GUID Fix

Helios/Interfaces/Capabilities/IResetMonitorsObserver.cs, Helios/Interfaces/Profile/ProfileInterface.cs, Patching/DCS/MonitorSetup.cs, Profile Editor/MainWindow.xaml.cs
internal: significantly changed shadow monitor tracking
internal: monitor setup now defers all geometry changes until after reset
fixes #294
=> fixed reset monitors with multiple identically sized displays out of order

Helios/Interfaces/DCS/M2000C/M2000CInterface.cs
See https://github.com/HeliosVirtualCockpit/Helios/issues/82
Adds the following interfaces:
One 3-way switch (Fuel Panel Detotalizer switch)
Eight 3-way switches (VTB side switches)
One 2-way switch (VTB declutter switch)
=> Basic M2000C Capability

HeliosFalcon/Interfaces/BMS/BMSFalconDataExporter.cs
Current Theater Binding set value on profile start not after shared memory is available.
=> Current Theater Binding set value on profile start

HeliosFalcon/Controls/MapControl.cs
Syntax correction, functionally identical.
=> MapControl code correction

HeliosFalcon/Interfaces/BMS/BMSFalconDataExporter.cs, HeliosFalcon/Interfaces/FalconDataExporter.cs, HeliosFalcon/Interfaces/FalconInterface.cs
Poll flight data for current flight only and stop polling flight data whilst in the user interface.
=> Falcon Interface - Poll flight data for current flight only.

HeliosFalcon/Interfaces/BMS/BMSFalconDataExporter.cs
=> Falcon Interface - Poll flight data for current flight - modification.

HeliosFalcon/Interfaces/FalconInterface.cs
Reverts HeliosVirtualCockpit/Helios#466
=> Revert "Falcon Interface modified reset behaviour."

HeliosFalcon/Interfaces/FalconInterface.cs
=> Falcon Interface fix reset behaviour by modifying Current Theater update method.

Helios/Controls/Special/MemoryWire.cs, Helios/Helios.csproj
This is essentially a piece of wire with memory, simply sends any value on its input side to its output side and on a resend request sends any last values entered on its input side to its output side.
=> Added Memory Wire control.

Helios/Controls/ImageTranslucent.cs, Helios/Controls/ImageTranslucentAppearanceEditor.xaml, Helios/Controls/ImageTranslucentBehaviorEditor.xaml, Helios/Controls/ImageTranslucentBehaviorEditor.xaml.cs, Helios/Helios.csproj
ImageTranslucent Control:
This allows optional pass through interaction with any underlying controls.
=> Add ImageTranslucent Control - Allow Interaction with underlying controls

Helios/HeliosAction.cs, Helios/HeliosTrigger.cs, Helios/HeliosValue.cs
this restores the ability to assign explicit IDs to triggers, values, and actions
=> alternative fix for issue 486

HeliosFalcon/Gauges/Textures/FalconTextureDisplay.cs, HeliosFalcon/Interfaces/FalconInterface.cs, HeliosFalcon/Interfaces/FalconInterfaceEditor.xaml, HeliosFalcon/Interfaces/FalconInterfaceEditor.xaml.cs
Selectively apply the enhanced texture refresh rates to the HUD and MFDs only in order to reduce the impact of the additional processing load on the Falcon BMS frame rate.
Also added the option to select either Enhanced 90Hz, Enhanced 60Hz or Legacy 30hz texture refresh rates.
=> Falcon Interface Texture Refresh Rate Optimisation

Helios/Controls/HeliosPanelBehaviorEditor.xaml, Helios/Controls/HeliosPanelBehaviorEditor.xaml.cs
This prevents deselecting all checkboxes by unchecking an already checked checkbox.
=> Helios Panels - Fix for interaction selection checkboxes

HeliosFalcon/Interfaces/RTT/InterfaceEditor.xaml, HeliosFalcon/Interfaces/RTT/InterfaceEditor.xaml.cs
Allows only numeric input and updates source immediately on textbox text change.
=> Falcon Interface Editor - Fix for FramesPerSecond Textbox

HeliosFalcon/Controls/MapControlMapRenderer.cs
Falcon Interface MapControls - Label Reformatting
=> Falcon Interface MapControls - Label Reformatting

Helios/Interfaces/DCS/AH64D/AH-64DInterface.cs, Helios/Interfaces/DCS/Common/Switch.cs
Reverts HeliosVirtualCockpit/Helios#573 so that a fix can be added and brought in under a single PR
=> Revert "Incremental switch"

Helios/GlobalOptions.cs, Helios/HeliosBinding.cs, Helios/HeliosObject.cs, Helios/IBindingElement.cs, HeliosFalcon/Interfaces/BMS/BMSFalconDataExporter.cs, Profile Editor/GlobalOptionsWindow.xaml
[Falcon Interface - Add Ownship Orientation to Bullseye Binding](https://github.com/HeliosVirtualCockpit/Helios/commit/f5271a71f84242740bbe629d6b1cb6fc9a9dcce7)
[Reset all Lua Variables on a Profile Reset ](https://github.com/HeliosVirtualCockpit/Helios/commit/0965cf2fb273297fbaffb988154aa268c2463b3e)
=> Pulling in #606 and #607 from linknetx

Helios/Controls/DualIndicatorPushButton.cs, Helios/Controls/DualIndicatorPushButtonAppearanceEditor.xaml, Helios/Controls/DualIndicatorPushButtonAppearanceEditor.xaml.cs, Helios/Controls/Indicator.cs, Helios/Controls/IndicatorPushButton.cs, Helios/Controls/PushButton.cs, Helios/Controls/PushButtonAppearanceEditor.xaml, Helios/Controls/RockerSwitch.cs, Helios/Controls/RockerSwitchAppearanceEditor.xaml, Helios/Windows/Controls/HeliosVisualView.cs
Various changes to correct font scaling for controls.  This PR also adds font scaling for Rockers and Pushbuttons.
The attached profile was used for testing.
[Indicator Test Profile.zip](https://github.com/HeliosVirtualCockpit/Helios/files/9951182/Indicator.Test.Profile.zip)
=> 637 indicator fontsize is scaled on profile load since 1654002

Helios/ConfigManager.cs, Helios/Helios.csproj, Helios/Interfaces/Helios/HeliosInformationInterface.cs, Helios/Interfaces/Helios/HeliosInformationInterfaceEditor.xaml, Helios/Interfaces/Helios/HeliosInformationInterfaceEditor.xaml.cs
Added Binding for the currently running Helios Version number,
=> Added Binding for Helios Version Number

Helios/Helios.csproj, Helios/Interfaces/DCS/FA18C/FA18CInterface.cs
Fix for #644 which was a misfunctioning Parking Brake on the Hornet.  This is a fix to the style 1 interface, but will be generated to fix  the JSON version of the interface.
=> 644 fa 18c parking brake interface malfunction

Helios/Interfaces/DirectX/DirectXControllerAxis.cs, Helios/Interfaces/DirectX/DirectXControllerInterface.cs
#485 protection and additional diagnostics for this issue which seems to be a slider issue.
#491 and #659 seem to be the same problem and again this PR is to add protection and provide extra diagnostic messages.  
@Todd1215 fancy reviewing this for me?
=> Changes to help diagnose DirectX problems

Helios.sln, Helios/Helios.csproj, Helios/Interfaces/DirectX/DirectXControllerInterface.cs, Helios/Interfaces/DirectX/Functions/IHotasFunctions.cs, Helios/Interfaces/DirectX/Functions/ThrustmasterWarthogThrottleIndicators.cs, Helios/Interfaces/DirectX/Functions/VirpilHotasIndicators.cs, Helios/packages.config, VendorUsbCommunications/App.config, VendorUsbCommunications/Program.cs, VendorUsbCommunications/Properties/AssemblyInfo.cs, VendorUsbCommunications/VendorUsbCommunications.csproj
Vendor specific capabilities have been added to the DirectX interface to allow actions to control the leds on the Thrustmaster Warthog Throttle and the Virpil HOTAS.
=> 133 direct access to warthog hotas leds

Helios/Windows/Controls/ColorPickerDialog.xaml, Helios/Windows/Controls/ColorPickerDialog.xaml.cs, Helios/Windows/Controls/FontChooserDialog.xaml, Helios/Windows/Controls/FontChooserDialog.xaml.cs
Feature to allow saving and restoration of colour values and font settings within Profile Editor.
=> Option to store settings for ColorWell and FontSelection

Aircraft CH-47F Plugin/Interfaces/CH-47FInterface.cs, Helios/Controls/ClickType.cs, Helios/Controls/PotentiometerBehaviorEditor.xaml.cs, Helios/Controls/PotentiometerClickable.cs, Helios/Controls/PotentiometerClickableAppearanceEditor.xaml, Helios/Controls/PotentiometerClickableAppearanceEditor.xaml.cs, Helios/Controls/PotentiometerIndcatorClickable.cs, Helios/Controls/PotentiometerKnob.cs, Helios/Controls/Rotary.cs, Helios/Controls/RotaryEncoderClickable.cs, Helios/Controls/RotaryInteractionEditor.xaml, Helios/Controls/RotaryKnob.cs, Helios/Helios.csproj, InterfaceFiles/InterfaceFiles.csproj
…h also has an indicator function.  Changes to the CH-47F interface to better support the Fire Handles.
=> Potentiometer which is clickable at the centre and which has indication
